# Changes here will be overwritten by Copier
_commit: 0b9cfe5
_src_path: gh:audivir/copier-template
author_email: pypi@audivir.de
author_name: Tim Hörmann
description: Simple HTTP API consumer based on `httpx` and `msgspec`.
github_org: audivir
project_name: mxhttp
project_slug: mxhttp
project_type: python
